### ISSUE TITLE
CREATE (UNIQUE) INDEX statement in table files are not sorted

### ISSUE THREAD

**Issue by yvesf** [qwazer/scheme2ddl#44] opened 2016-06-23 08:26 UTC
Between two exports the ordering of the index statements on a table can vary.
This creates annoying diffs if you use git on these files.
I think it would be beneficial to explicitly sort the the dependent objects by name or so.

**Comment by dvsidamore** [comment] 2018-10-31 07:52
I have same problem. Does anybody solved it?

![image](https://user-images.githubusercontent.com/44634201/47773367-dfd4cc80-dcfa-11e8-8c2e-fa3800c5ba5d.png)

**Comment by qwazer** [comment] 2018-10-31 17:03
@dvsidamore I'll try to fix in near future (probably, on weekend). Thanks for reminding.

**Comment by qwazer** [comment] 2018-11-04 17:20
The root cause: `DBMS_METADATA.GET_DEPENDENT_DDL` return `CREATE (UNIQUE|BITMAP)? INDEX` statements sorted by creation date.
I decided to parse `DBMS_METADATA.GET_DEPENDENT_DDL` on separate`CREATE (UNIQUE|BITMAP)? INDEX ` statements and sort these alphanumerically in `DDLFormatter` class.

So order for 3 indexes `UNIQUE INDEX a`, ` INDEX b` , `BITMAP INDEX c` will be:
```
CREATE BITMAP INDEX c...
CREATE INDEX b ..
CREATE UNIQUE INDEX a..
```

Fixed in PR #53 
New parameter of DDLFormatter `sortCreateIndexStatements` with default value `true` added.

**Comment by qwazer** [comment] 2018-11-04 18:04
fixed in [v2.4.2](https://github.com/qwazer/scheme2ddl/releases/tag/v2.4.2)

**Closed by qwazer** 2018-11-04 18:04 UTC

**Comment by qwazer** [comment] 2018-11-04 19:28
After implementing this, I found, that possibly it should be implemented in other way as proposed in https://github.com/qwazer/scheme2ddl/issues/20#issuecomment-83579410

**Comment by dvsidamore** [comment] 2018-11-13 08:31
thanks a lot!
